my_name=["asit","asittttt","garabadu","pen"]
print(my_name[0])
print(my_name[-1])
my_name[1]="asiyt"
print(my_name[1])
#adding
my_name.append("iter")
print(my_name)
my_name.extend("cool")
print(my_name)
